import { Brain, FileText, Sparkles, ArrowRight, Search, Plus } from "lucide-react";
import "../globals.css";

const notes = [
  { title: "Anatomy — Chapter 1", meta: "Exam Notes · 12 pages", tag: "Ready" },
  { title: "Physiology — Cell Membrane", meta: "Quick Revision · 4 pages", tag: "Ready" },
  { title: "Chemistry — Lecture 03", meta: "Detailed Notes · 9 pages", tag: "Draft" },
];

export default function Notes() {
  return <main className="min-h-screen bg-[#f7f8fc] text-slate-950"><div className="mx-auto max-w-6xl p-6 md:p-10"><header className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Study workspace</p><h1 className="mt-2 text-3xl font-black tracking-tight">Smart Notes</h1><p className="mt-2 text-sm text-slate-500">Turn your source material into notes that are made for understanding and revision.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-extrabold text-white"><Plus size={17}/> Create notes</button></header>
<div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-950 p-5 text-white md:col-span-2"><div className="flex items-center gap-2 text-xs font-bold text-slate-300"><Sparkles size={15}/> AI NOTE GENERATOR</div><h2 className="mt-4 text-2xl font-black">What are you studying?</h2><p className="mt-2 max-w-lg text-sm leading-6 text-slate-400">Choose your course and source, then generate quick, detailed, exam-focused or last-minute revision notes.</p><button className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-extrabold text-slate-950">Generate from material <ArrowRight size={16}/></button></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid size-11 place-items-center rounded-xl bg-slate-100"><Brain size={20}/></div><h3 className="mt-5 font-black">One source → many formats</h3><p className="mt-2 text-sm leading-6 text-slate-500">Quick notes, detailed notes, exam notes, definitions, key points and cheat sheets.</p></div></div>
<div className="mt-10 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-xl font-black">Your notes</h2><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-400"><Search size={16}/>Search notes...</div></div><div className="mt-4 grid gap-4 md:grid-cols-3">{notes.map(n=><article key={n.title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="grid size-11 place-items-center rounded-xl bg-slate-100"><FileText size={19}/></div><h3 className="mt-5 font-extrabold">{n.title}</h3><p className="mt-2 text-xs text-slate-400">{n.meta}</p><span className="mt-5 inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{n.tag}</span></article>)}</div></div></main>;
}
