create extension if not exists pgcrypto;
create extension if not exists vector;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now()
);

create table if not exists courses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  code text,
  created_at timestamptz not null default now()
);

create table if not exists materials (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references courses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  mime_type text not null,
  size bigint not null default 0,
  storage_path text not null,
  extracted_text text,
  status text not null default 'uploaded' check (status in ('uploaded','processing','ready','failed')),
  created_at timestamptz not null default now()
);

create table if not exists material_chunks (
  id bigint generated by default as identity primary key,
  material_id uuid not null references materials(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  chunk_index int not null,
  content text not null,
  embedding vector(384),
  created_at timestamptz not null default now()
);

create table if not exists study_notes (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references courses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists quizzes (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references courses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  questions jsonb not null default '[]',
  question_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists study_attempts (
  id uuid primary key default gen_random_uuid(),
  quiz_id uuid not null references quizzes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  score numeric not null default 0,
  correct integer not null default 0,
  attempted integer not null default 0,
  completed_at timestamptz not null default now()
);

create index if not exists courses_user_id_idx on courses(user_id);
create index if not exists materials_user_id_idx on materials(user_id);
create index if not exists materials_course_id_idx on materials(course_id);
create index if not exists chunks_user_id_idx on material_chunks(user_id);
create index if not exists chunks_material_id_idx on material_chunks(material_id);
create index if not exists study_notes_user_id_idx on study_notes(user_id);
create index if not exists study_notes_course_id_idx on study_notes(course_id);
create index if not exists quizzes_user_id_idx on quizzes(user_id);
create index if not exists attempts_user_id_idx on study_attempts(user_id);

alter table profiles enable row level security;
alter table courses enable row level security;
alter table materials enable row level security;
alter table material_chunks enable row level security;
alter table study_notes enable row level security;
alter table quizzes enable row level security;
alter table study_attempts enable row level security;

create policy "profiles own" on profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "courses own" on courses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "materials own" on materials for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "chunks own" on material_chunks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notes own" on study_notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "quizzes own" on quizzes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "attempts own" on study_attempts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.match_material_chunks(
  query_embedding vector(384),
  match_threshold double precision,
  match_count integer,
  requested_user_id uuid
)
returns table (
  id bigint,
  material_id uuid,
  content text,
  chunk_index integer,
  similarity double precision
)
language sql
stable
as $$
  select mc.id,
         mc.material_id,
         mc.content,
         mc.chunk_index,
         1 - (mc.embedding <=> query_embedding) as similarity
  from public.material_chunks mc
  where mc.user_id = requested_user_id
    and mc.embedding is not null
    and 1 - (mc.embedding <=> query_embedding) >= match_threshold
  order by mc.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 50);
$$;
