"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { ArrowLeft, FileText, Loader2, UploadCloud } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

export default function CourseDetail({ params }: { params: Promise<{ id: string }> }) {
  const supabase = createSupabaseBrowserClient();
  const [id, setId] = useState(""); const [course, setCourse] = useState<any>(null); const [materials, setMaterials] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void params.then(({id})=>setId(id)); }, [params]);
  useEffect(() => { if (!id) return; void load(); }, [id]);
  async function load() { const {data}=await supabase.auth.getSession(); if(!data.session){window.location.href="/login";return;} const r=await fetch(`/api/courses/${id}`,{headers:{Authorization:`Bearer ${data.session.access_token}`}}); const d=await r.json(); if(!r.ok){setError(d.error||"Could not load course.");setLoading(false);return;} setCourse(d.course);setMaterials(d.materials||[]);setLoading(false); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file=event.target.files?.[0]; if(!file)return; setUploading(true);setError(""); const {data}=await supabase.auth.getSession(); if(!data.session){window.location.href="/login";return;} const form=new FormData();form.append("file",file);form.append("courseId",id); const r=await fetch("/api/materials/upload",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`},body:form}); const d=await r.json(); if(!r.ok){setError(d.error||"Upload failed.");setUploading(false);return;} setMaterials(m=>[d.material,...m]); setUploading(false); try { const p=await fetch("/api/materials/process",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({materialId:d.material.id})}); const pd=await p.json(); if(!p.ok)setError(pd.error||"Processing failed."); else setMaterials(m=>m.map(x=>x.id===d.material.id?{...x,status:"ready"}:x)); } catch { setError("Material uploaded, but processing could not be completed."); } }
  if(loading)return <main className="grid min-h-screen place-items-center bg-[#f7f8fc]"><Loader2 className="animate-spin"/></main>;
  return <main className="min-h-screen bg-[#f7f8fc] text-slate-950"><div className="mx-auto max-w-6xl p-6 md:p-10"><a href="/courses" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-950"><ArrowLeft size={16}/> Courses</a><header className="mt-6 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Course</p><h1 className="mt-2 text-3xl font-black tracking-tight">{course?.title}</h1><p className="mt-2 text-sm text-slate-500">{course?.code||"Your private study knowledge base"}</p></div><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-extrabold text-white">{uploading?<Loader2 size={17} className="animate-spin"/>:<UploadCloud size={17}/>} Upload material<input type="file" className="hidden" accept=".pdf,.pptx,.docx,.txt,.png,.jpg,.jpeg,.webp" onChange={upload} disabled={uploading}/></label></header>{error&&<p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-black">Course material</h2><span className="text-xs text-slate-400">{materials.length} file{materials.length===1?"":"s"}</span></div>{materials.length===0?<div className="mt-6 rounded-xl border border-dashed border-slate-200 bg-slate-50 p-10 text-center"><UploadCloud className="mx-auto text-slate-300"/><p className="mt-3 text-sm font-bold">No material yet</p><p className="mt-1 text-xs text-slate-400">Upload a PDF, DOCX, PPTX, TXT or supported image to start.</p></div>:<div className="mt-5 divide-y divide-slate-100">{materials.map(m=><div key={m.id} className="flex items-center gap-4 py-4"><div className="grid size-11 place-items-center rounded-xl bg-slate-100"><FileText size={18}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{m.name}</p><p className="mt-1 text-xs text-slate-400">{m.mime_type} · {(m.size/1024/1024).toFixed(1)} MB</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-[11px] font-bold capitalize">{m.status}</span></div>)}</div>}</section></div></main>;
}
