"use client";

import { useEffect, useState } from "react";
import { Presentation, Sparkles, FileText, WandSparkles, Trash2, Download, Save, RotateCcw, ChevronLeft, ChevronRight } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import "../globals.css";

type Material = { id: string; name: string; status: string | null };
type Slide = { title: string; keyPoints: string[]; visual: string; speakerNotes: string };
type Deck = { id: string; title: string; course_id: string; material_id: string | null; slides: Slide[]; created_at: string; updated_at: string };

export default function Presentations() {
 const [materials,setMaterials]=useState<Material[]>([]),[decks,setDecks]=useState<Deck[]>([]),[materialId,setMaterialId]=useState(""),[topic,setTopic]=useState(""),[slides,setSlides]=useState(10),[activeDeck,setActiveDeck]=useState<Deck|null>(null),[activeSlide,setActiveSlide]=useState(0),[loading,setLoading]=useState(true),[generating,setGenerating]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function headers(json=false){const {data:{session}}=await createSupabaseBrowserClient().auth.getSession();if(!session?.access_token)throw new Error("Sign in to use presentations.");return json?{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"}:{Authorization:`Bearer ${session.access_token}`};}
 async function load(){setLoading(true);try{const h=await headers();const [a,b]=await Promise.all([fetch("/api/materials",{headers:h,cache:"no-store"}),fetch("/api/presentations",{headers:h,cache:"no-store"})]);const m=await a.json(),p=await b.json();if(!a.ok)throw new Error(m.error||"Could not load materials.");if(!b.ok)throw new Error(p.error||"Could not load presentations.");const ready=(m.materials??[]).filter((x:Material)=>x.status==="ready");setMaterials(ready);setDecks(p.presentations??[]);if(!materialId&&ready[0])setMaterialId(ready[0].id);}catch(e){setError(e instanceof Error?e.message:"Could not load presentations.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function generate(){if(!materialId||generating)return;setGenerating(true);setError("");try{const r=await fetch("/api/study/generate",{method:"POST",headers:await headers(true),body:JSON.stringify({action:"presentation",materialId,title:topic.trim()||undefined,options:{topic:topic.trim()||"Study Topic",slides}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Presentation generation failed.");setDecks(x=>[d.presentation,...x.filter(v=>v.id!==d.presentation.id)]);setActiveDeck(d.presentation);setActiveSlide(0)}catch(e){setError(e instanceof Error?e.message:"Presentation generation failed.")}finally{setGenerating(false)}}
 async function save(){if(!activeDeck||saving)return;setSaving(true);try{const r=await fetch("/api/presentations",{method:"PATCH",headers:await headers(true),body:JSON.stringify({id:activeDeck.id,title:activeDeck.title,slides:activeDeck.slides})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed.");setActiveDeck(d.presentation);setDecks(x=>x.map(v=>v.id===d.presentation.id?d.presentation:v))}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setSaving(false)}}
 async function remove(id:string){try{const r=await fetch("/api/presentations",{method:"DELETE",headers:await headers(true),body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Delete failed.");setDecks(x=>x.filter(v=>v.id!==id));if(activeDeck?.id===id)setActiveDeck(null)}catch(e){setError(e instanceof Error?e.message:"Delete failed")}}
 async function exportDeck(id:string){try{const r=await fetch(`/api/presentations/export?id=${id}`,{headers:await headers()});if(!r.ok)throw new Error((await r.json()).error||"Export failed.");const url=URL.createObjectURL(await r.blob()),a=document.createElement("a");a.href=url;a.download=`${(activeDeck?.title||"presentation").replace(/[^a-z0-9-_]+/gi,"-")}.pptx`;a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"Export failed")}}
 function patchSlide(p:Partial<Slide>){if(!activeDeck)return;setActiveDeck({...activeDeck,slides:activeDeck.slides.map((s,i)=>i===activeSlide?{...s,...p}:s)})}
 return <main className="min-h-screen bg-[#f7f8fc] text-slate-950"><div className="mx-auto max-w-6xl p-6 md:p-10"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Creation studio</p><h1 className="mt-2 text-3xl font-black">Presentations</h1><p className="mt-2 text-sm text-slate-500">Generate, edit, persist and export source-grounded presentations.</p></header>
 <div className="mt-8 rounded-3xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-2 text-xs font-bold text-slate-300"><Sparkles size={15}/> SOURCE → SLIDES</div><h2 className="mt-4 text-3xl font-black">Create from your ready material.</h2><div className="mt-7 grid gap-3 md:grid-cols-[1.4fr_1fr_auto]"><select value={materialId} onChange={e=>setMaterialId(e.target.value)} disabled={loading||generating||!materials.length} className="rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm font-semibold text-white"><option value="" className="text-slate-950">{loading?"Loading…":materials.length?"Select material":"No ready material"}</option>{materials.map(m=><option key={m.id} value={m.id} className="text-slate-950">{m.name}</option>)}</select><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Presentation topic" className="rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm text-white outline-none"/><button onClick={generate} disabled={!materialId||generating} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-slate-950 disabled:opacity-40"><WandSparkles size={16}/>{generating?"Generating…":"Create with AI"}</button></div><div className="mt-3"><select value={slides} onChange={e=>setSlides(Number(e.target.value))} className="rounded-lg border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-bold text-white"><option value={6}>6 slides</option><option value={10}>10 slides</option><option value={15}>15 slides</option></select></div></div>
 {error&&<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-800">{error}</div>}
 {activeDeck&&<section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><input value={activeDeck.title} onChange={e=>setActiveDeck({...activeDeck,title:e.target.value})} className="text-xl font-black outline-none"/><p className="text-xs text-slate-400">Slide {activeSlide+1} of {activeDeck.slides.length} · persistent</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white"><Save size={14}/>{saving?"Saving…":"Save"}</button><button onClick={()=>void exportDeck(activeDeck.id)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold"><Download size={14}/> Export PPTX</button><button onClick={()=>void remove(activeDeck.id)} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-4 py-2.5 text-xs font-bold text-rose-600"><Trash2 size={14}/> Delete</button><button onClick={generate} disabled={generating||!materialId} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold"><RotateCcw size={14}/> Regenerate</button></div></div><article className="mt-6 rounded-2xl bg-slate-950 p-7 text-white"><input value={activeDeck.slides[activeSlide]?.title||""} onChange={e=>patchSlide({title:e.target.value})} className="w-full bg-transparent text-2xl font-black outline-none"/><textarea value={(activeDeck.slides[activeSlide]?.keyPoints||[]).join("\n")} onChange={e=>patchSlide({keyPoints:e.target.value.split("\n").filter(Boolean)})} className="mt-5 min-h-44 w-full rounded-xl border border-white/10 bg-white/5 p-4 text-sm leading-7 text-slate-200 outline-none"/><textarea value={activeDeck.slides[activeSlide]?.speakerNotes||""} onChange={e=>patchSlide({speakerNotes:e.target.value})} className="mt-4 min-h-24 w-full rounded-xl border border-white/10 bg-white/5 p-4 text-xs leading-6 text-slate-300 outline-none" placeholder="Speaker notes"/><p className="mt-4 text-xs text-slate-500">Suggested visual: {activeDeck.slides[activeSlide]?.visual||"—"}</p></article><div className="mt-4 flex justify-between"><button onClick={()=>setActiveSlide(i=>Math.max(0,i-1))} disabled={!activeSlide} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold disabled:opacity-40"><ChevronLeft size={15}/> Previous</button><button onClick={()=>setActiveSlide(i=>Math.min(activeDeck.slides.length-1,i+1))} disabled={activeSlide>=activeDeck.slides.length-1} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold">Next <ChevronRight size={15}/></button></div></section>}
 <section className="mt-10 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex justify-between"><h2 className="font-black">Saved presentations</h2><span className="text-xs text-slate-400">{decks.length} saved</span></div>{decks.length?<div className="mt-5 grid gap-3 md:grid-cols-2">{decks.map(d=><button key={d.id} onClick={()=>{setActiveDeck(d);setActiveSlide(0)}} className="rounded-xl border p-4 text-left hover:shadow-md"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-slate-100"><Presentation size={18}/></div><div><p className="text-sm font-extrabold">{d.title}</p><p className="text-xs text-slate-400">{d.slides.length} slides</p></div></div></button>)}</div>:<div className="mt-5 rounded-xl border border-dashed p-8 text-center text-sm text-slate-400">No saved presentations yet.</div>}</section><div className="mt-8 grid gap-4 md:grid-cols-3">{[{i:FileText,t:"Choose source",d:"Use a ready indexed material."},{i:WandSparkles,t:"Generate",d:"AI creates structured slides and notes."},{i:Presentation,t:"Export",d:"Edit, save and export a real PPTX."}].map(({i:Icon,t,d})=><div key={t} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid size-11 place-items-center rounded-xl bg-slate-100"><Icon size={19}/></div><h3 className="mt-5 font-black">{t}</h3><p className="mt-2 text-sm text-slate-500">{d}</p></div>)}</div></div></main>;
}
