import { Presentation, Sparkles, Upload, FileText, ArrowRight, WandSparkles } from "lucide-react";
import "../globals.css";

export default function Presentations() {
 return <main className="min-h-screen bg-[#f7f8fc] text-slate-950"><div className="mx-auto max-w-6xl p-6 md:p-10"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Creation studio</p><h1 className="mt-2 text-3xl font-black tracking-tight">Presentations</h1><p className="mt-2 text-sm text-slate-500">Turn lectures, PDFs and notes into polished academic presentations.</p></header>
 <div className="mt-8 rounded-3xl bg-slate-950 p-7 text-white md:p-10"><div className="flex items-center gap-2 text-xs font-bold text-slate-300"><Sparkles size={15}/> SOURCE → SLIDES</div><h2 className="mt-4 text-3xl font-black">Create a presentation in minutes.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Choose a source, tell UMAIR HUB your topic and let the AI build the outline, slide content, visuals and speaker notes.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-slate-950"><WandSparkles size={16}/> Create with AI</button><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/10 px-5 py-3 text-sm font-bold text-white"><Upload size={16}/> Import PPT/PDF</button></div></div>
 <div className="mt-10 grid gap-4 md:grid-cols-3">{[{i:FileText,t:"Choose source",d:"Use your course material so slides stay grounded."},{i:WandSparkles,t:"Generate outline",d:"Control slide count, audience and presentation style."},{i:Presentation,t:"Present confidently",d:"Get speaker notes, Q&A and presentation practice."}].map(({i:Icon,t,d})=><div key={t} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid size-11 place-items-center rounded-xl bg-slate-100"><Icon size={19}/></div><h3 className="mt-5 font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div>
 <div className="mt-10 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-black">Your presentations</h2><span className="text-xs text-slate-400">No presentations yet</span></div><div className="mt-6 rounded-xl border border-dashed border-slate-200 p-8 text-center"><Presentation className="mx-auto text-slate-300"/><p className="mt-3 text-sm font-bold">Your generated decks will appear here.</p><button className="mt-4 inline-flex items-center gap-2 text-sm font-extrabold">Create your first deck <ArrowRight size={15}/></button></div></div>
 </div></main>;
}
